parse_config:
  zmk_additional_includes:
    - "modules/zmk/helpers/include"

  zmk_preamble: |
    #include <zmk-helpers/key-labels/42.h>
    #define CONFIG_WIRELESS

  raw_binding_map:
    "&sys_reset": Reset
    "&bootloader": Boot
    "&caps_word": Caps Word

    "&bt BT_SEL 0": { left: "$$mdi:bluetooth$$", right: "1" }
    "&bt BT_SEL 1": { left: "$$mdi:bluetooth$$", right: "2" }
    "&bt BT_SEL 2": { left: "$$mdi:bluetooth$$", right: "3" }
    "&bt BT_SEL 3": { left: "$$mdi:bluetooth$$", right: "4" }
    "&bt BT_CLR": $$mdi:bluetooth-off$$

    "&out OUT_USB": { left: "$$mdi:keyboard$$", right: "$$mdi:usb$$" }
    "&out OUT_BLE": { left: "$$mdi:keyboard$$", right: "$$mdi:bluetooth$$" }

    "&kp LG(C)": $$mdi:content-copy$$
    "&kp LG(X)": $$mdi:content-cut$$
    "&kp LG(V)": $$mdi:content-paste$$
    "&kp LG(Q)": "Win\nClose"

    "&dot_spc": Sentence
    "&num_dance": { "t": "Smart\nNum",  }
    "&better_shift LSHFT 0": { "t": "Better\nShift" }

    "&kp LC(SPACE)": Tmux
    # "&kp LA(Q)": Quit App
    "&minus_plus": { "t": "-", "s": "+" }
    "&excl_at": { "t": "!", "s": "@" }
    "&comma_morph": { "t": ",", "s": ";",  }
    "&dot_morph": { "t": ".", "s": ":",  }
    "&lpar_lt": { "t": "(", "s": "<" }
    "&rpar_gt": { "t": ")", "s": ">" }
    "&fslh_astrk": { "t": "/", "s": "*" }
    "&grave_bslh": { "t":"`", "s":"\\"}

    # Mouse
    "&smart_mouse": $$mdi:mouse$$
    "&mmv MOVE_UP": { left: "$$mdi:mouse$$", right: "$$mdi:arrow-up$$" }
    "&mmv MOVE_DOWN": { left: "$$mdi:mouse$$", right: "$$mdi:arrow-down$$" }
    "&mmv MOVE_LEFT": { left: "$$mdi:mouse$$", right: "$$mdi:arrow-left$$" }
    "&mmv MOVE_RIGHT": { left: "$$mdi:mouse$$", right: "$$mdi:arrow-right$$" }
    "&msc SCRL_UP": { left: "$$mdi:mouse-scroll-wheel$$", right: "$$mdi:arrow-up-circle$$" }
    "&msc SCRL_DOWN": { left: "$$mdi:mouse-scroll-wheel$$", right: "$$mdi:arrow-down-circle$$" }
    "&msc SCRL_LEFT": { left: "$$mdi:mouse-scroll-wheel$$", right: "$$mdi:arrow-left-circle$$" }
    "&msc SCRL_RIGHT": { left: "$$mdi:mouse-scroll-wheel$$", right: "$$mdi:arrow-right-circle$$" }
    "&mkp LCLK": $$mdi:mouse-left-click$$
    "&mkp RCLK": $$mdi:mouse-right-click$$
    "&mkp MCLK": $$mdi:mouse$$

  trans_legend: { "t": "", "type": "trans" }

  zmk_combos:
    # Horizontal combos
    combo_hash: { l: ["Horizontal Combos"] }
    combo_star: { l: ["Horizontal Combos"] }
    combo_caret: { l: ["Horizontal Combos"] }
    combo_dllr: { l: ["Horizontal Combos"] }
    combo_prcnt: { align: bottom, l: ["Horizontal Combos"] }
    combo_cut: { align: bottom, l: ["Horizontal Combos"] }
    combo_copy: { l: ["Horizontal Combos"] }
    combo_paste: { l: ["Horizontal Combos"] }
    combo_lbrc: { l: ["Horizontal Combos", "num"] }
    combo_rbrc: { l: ["Horizontal Combos", "num"] }
    combo_lpar: { l: ["Horizontal Combos", "num"] }
    combo_rpar: { l: ["Horizontal Combos", "num"] }
    combo_equal: { align: top, o: 1.5, arc_scale: 1.15, l: ["Horizontal Combos", "num"] }
    combo_under: { align: top, o: 2, arc_scale: 1.15, l: ["Horizontal Combos"] }
    combo_lbkt: { l: ["Horizontal Combos", "num"] }
    combo_rbkt: { l: ["Horizontal Combos", "num"] }

    # Vertical combos
    combo_tilde: { l: ["Vertical Combos"] }
    combo_amps: { l: ["Vertical Combos"] }
    combo_grave: { l: ["Vertical Combos"] }
    combo_bslh: { l: ["Vertical Combos"] }
    combo_pipe: { l: ["Vertical Combos"] }
    combo_plus: { l: ["Vertical Combos"] }
    combo_fslh: { l: ["Vertical Combos"] }
    combo_dot_v: { l: ["Vertical Combos"] }
    combo_under: { align: bottom, l: ["Horizontal Combos"] }
    combo_minus: { l: ["Vertical Combos"] }
    combo_colon: { l: ["Vertical Combos"] }

  zmk_keycode_map:
    # custom mappings
    LALT: $$mdi:apple-keyboard-option$$
    RALT: $$mdi:apple-keyboard-option$$
    LCTRL: $$mdi:apple-keyboard-control$$
    RCTRL: $$mdi:apple-keyboard-control$$
    LGUI: $$mdi:apple-keyboard-command$$
    RGUI: $$mdi:apple-keyboard-command$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$

    BSPC: $$mdi:backspace$$
    DEL: $$mdi:backspace-reverse$$
    ESC: "ESC" 
    RET: $$mdi:keyboard-return$$
    SPACE: $$mdi:keyboard-space$$
    TAB: $$mdi:keyboard-tab$$

    PG_UP: PgUp
    PG_DN: PgDn
    INS: Ins
    HOME: Home
    END: End

    UP: "↑"
    DOWN: "↓"
    LEFT: "←"
    RIGHT: "→"

    C_MUTE: $$mdi:volume-off$$
    C_PP: $$mdi:play-pause$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-medium$$
    C_NEXT: $$mdi:skip-forward$$
    C_PREV: $$mdi:skip-backward$$

    # defaults
    AMPERSAND: "&"
    AMPS: "&"
    APOS: "'"
    APOSTROPHE: "'"
    ASTERISK: "*"
    ASTRK: "*"
    AT: "@"
    AT_SIGN: "@"
    BACKSLASH: \
    BSLH: \
    CARET: ^
    COLON: ":"
    COMMA: ","
    DLLR: $
    DOLLAR: $
    DOT: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    EQUAL: "="
    EXCL: "!"
    EXCLAMATION: "!"
    FSLH: /
    GRAVE: "`"
    GREATER_THAN: ">"
    GT: ">"
    HASH: "#"
    LBKT: "["
    LBRC: "{"
    LEFT_BRACE: "{"
    LEFT_BRACKET: "["
    LEFT_PARENTHESIS: (
    LESS_THAN: <
    LPAR: (
    LT: <
    MINUS: "-"
    NON_US_BACKSLASH: \
    NON_US_BSLH: "|"
    NON_US_HASH: "#"
    NUHS: "#"
    PERCENT: "%"
    PERIOD: .
    PIPE: "|"
    PIPE2: "|"
    PLUS: +
    POUND: "#"
    PRCNT: "%"
    QMARK: "?"
    QUESTION: "?"
    RBKT: "]"
    RBRC: "}"
    RIGHT_BRACE: "}"
    RIGHT_BRACKET: "]"
    RIGHT_PARENTHESIS: )
    RPAR: )
    SEMI: ;
    SEMICOLON: ;
    SINGLE_QUOTE: "'"
    SLASH: /
    SQT: "'"
    STAR: "*"
    TILDE: "~"
    TILDE2: "~"
    UNDER: _
    UNDERSCORE: _

draw_config:
  # Bigger keys for more text
  key_w: 80
  key_h: 80
  combo_w: 36
  combo_h: 40

  # Layout
  append_colon_to_layer_header: false
  dark_mode: true
  footer_text: "Boardsource BLE Corne"

  # Glyphs
  glyph_tap_size: 26
  glyph_hold_size: 20
  glyph_shifted_size: 18
  glyph_urls:
    mdi: "https://raw.githubusercontent.com/Templarian/MaterialDesign-SVG/master/svg/{}.svg"
    tabler: "https://raw.githubusercontent.com/tabler/tabler-icons/master/icons/outline/{}.svg"

  # Gruvbox Dark Theme
  svg_extra_style: |
    svg.keymap {
      font-family: "GeistMono Nerd Font", "Fira Code", SFMono-Regular, Consolas, monospace;
      font-size: 16px;
      font-weight: 500;
    }
    rect.key {
      fill: #3c3836;
      stroke: #504945;
      stroke-width: 1.5;
    }
    rect.held {
      fill: #689d6a;
    }
    rect.combo {
      fill: #458588;
      stroke: #83a598;
    }
    path.combo {
      stroke: #83a598;
      stroke-width: 1.5;
    }
    rect.ghost {
      fill: #282828;
    }
    text {
      fill: #ebdbb2;
    }
    text.tap {
      fill: #ebdbb2;
      font-size: 18px;
    }
    text.hold {
      fill: #d79921;
      font-size: 13px;
      translate: 0 -4px;
    }
    .glyph.hold path, .glyph.hold {
      fill: #d79921;
      translate: 0 -3px;
    }
    text.shifted {
      fill: #fe8019;
      font-size: 13px;
      translate: 0 4px;
    }
    .combo text.shifted {
      font-size: 14px;
    }
    .combo .glyph path, .combo .glyph {
      fill: #ebdbb2;
    }
    .glyph.tap path, .glyph.tap {
      fill: #ebdbb2;
    }
    text.label {
      fill: #b8bb26;
      font-weight: bold;
    }
    text.layer-activator {
      fill: #8ec07c;
      font-style: italic;
      translate: 0 -4px;
    }
    .glyph.left, .glyph.right {
      transform: scale(1.5);
      fill: #ebdbb2;
    }
    .glyph.left {
      translate: 26px 0;
    }
    .glyph.right {
      translate: -24px 0;
    }
    text.left, text.right {
      font-size: 22px;
      fill: #ebdbb2;
    }
    text.left {
      translate: 20px 0;
    }
    text.right {
      translate: -18px 0;
    }
